# Generated by Django 3.0.6 on 2020-05-29 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
