# Generated by Django 3.0.6 on 2020-06-15 01:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pics', '0008_auto_20200613_1902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Post',
        ),
    ]
