# Generated by Django 3.0.6 on 2020-06-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0010_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
    ]
