# Generated by Django 3.0.6 on 2020-06-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0011_remove_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_avatar',
        ),
    ]
