# Generated by Django 3.0.6 on 2020-06-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0012_remove_profile_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='ProfilePicture/'),
        ),
    ]
