# Generated by Django 3.0.6 on 2020-06-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0013_auto_20200622_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(upload_to='ProfilePicture/'),
        ),
    ]
