# Generated by Django 3.0.6 on 2020-06-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0014_auto_20200622_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
