# Generated by Django 3.0.6 on 2020-06-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0015_auto_20200622_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
