# Generated by Django 3.0.6 on 2020-06-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0021_auto_20200627_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(upload_to='ProfilePicture/'),
        ),
    ]
