# Generated by Django 3.0.6 on 2020-06-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0022_auto_20200627_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='ProfilePicture/'),
        ),
    ]
