# Generated by Django 3.0.6 on 2020-07-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0024_comments_approved_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='Name',
        ),
    ]
